### PR TITLE
Fix compatibility with haskell-src-exts 1.21

### LINKED ISSUE #530: hindent fails to build with haskell-src-exts >=1.21
## Problem
```
cabal install hindent
```

Log message:
```
Configuring hindent-5.2.7...
Building hindent-5.2.7...
Failed to install hindent-5.2.7
Build log ( /home/exa/work/imcurses/.cabal-sandbox/logs/ghc-8.4.3/hindent-5.2.7-GqIdV7TJaGfJi2BnEdtl5Z.log ):
cabal: Entering directory '/tmp/cabal-tmp-27319/hindent-5.2.7'
Configuring hindent-5.2.7...
Preprocessing library for hindent-5.2.7..
Building library for hindent-5.2.7..
[1 of 4] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/CabalFile.o )
[2 of 4] Compiling HIndent.Types    ( src/HIndent/Types.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/Types.o )
[3 of 4] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:453:10: error:
    Duplicate instance declarations:
      instance Pretty Type -- Defined at src/HIndent/Pretty.hs:453:10
      instance Pretty Kind -- Defined at src/HIndent/Pretty.hs:1475:10
    |
453 | instance Pretty Type where
    |          ^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-27319/hindent-5.2.7'
cabal: Error: some packages failed to install:
hindent-5.2.7-GqIdV7TJaGfJi2BnEdtl5Z failed during the building phase. The
exception was:
ExitFailure 1
```

# Cause

This is because haskell-src-exts converted `Kind` from `data Kind l = ...` to `type Kind = Type` in version `1.21`.

# Solution

The obvious immediate workaround is to fix the dependency to explicitly say `<1.21`.

In my very humble opinion, just erasing the `Pretty Kind` instance should work too, but not sure about consequences (the implementations differ, `Kind` has `pretty'`, `Type` has `typ`).

Thanks in advance!

### PR DESCRIPTION
**Pull request by felixonmars**
This fixes #530, all tests pass here.

I am very new to haskell, please let me know if I did anything wrong!

### CODE REVIEW

**Comment by domenkozar** [comment]
@chrisdone Could this be merged? I'm hoping it can also fix https://github.com/chrisdone/hindent/pull/537

**Comment by chrisdone** [comment]
Sure!
