### ISSUE TITLE
(more) inaccurate version bounds in .cabal file 

### ISSUE THREAD

**Issue by hvr** [chrisdone/hindent#205]
Since #203 has been locked, I have to follow-up here:

I just discovered that the missing upper bounds on HSE weren't the only inaccuracy:

`hindent-4.6.2` through `hindent-5.0.0` fail to build with base-4.7 even though it claims to support `base >= 4.7`;

specifically, for `hindent-4.6.2` through `hindent-4.6.4`:

```
src/HIndent/Pretty.hs:73:1-41: Warning:
    Module ‘Data.Monoid’ does not export ‘Alt’
[4 of 9] Compiling HIndent.Styles.Cramer ( src/HIndent/Styles/Cramer.hs, /tmp/hindent-4.6.2/dist-newstyle/build/x86_64-linux/ghc-7.8.4/hindent-4.6.2/build/HIndent/Styles/Cramer.o )

src/HIndent/Styles/Cramer.hs:12:32-37:
    Module ‘Data.List’ does not export ‘sortOn’
cabal: failed to build hindent-4.6.2
```

and for `hindent-5.0.0`:

```
Preprocessing library hindent-5.0.0...
[2 of 5] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, /tmp/hindent-5.0.0/dist-newstyle/build/x86_64-linux/ghc-7.8.4/hindent-5.0.0/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:949:26-29: Not in scope: ‘pure’

src/HIndent/Pretty.hs:954:39-42: Not in scope: ‘pure’
cabal: failed to build hindent-5.0.0
```

I can fix those on Hackage for you as well, but then it still remains to address the issue in the upstream source-tree: i.e. either restore compat with GHC 7.8, or fix the lower bound on `base`.

**Comment by chrisdone** [comment]
I'll update the base bound. :+1:

**Comment by tfausak** [comment]
It might be worth using [base-compat](https://www.stackage.org/package/base-compat) to fix stuff like this.

**Comment by chrisdone** [comment]
Added lower bounds on `base` for those versions, 5.0.1 supports GHC 7.8.
