### ISSUE TITLE
hindent fails to build with haskell-src-exts >=1.21

### ISSUE THREAD

**Issue by exaexa** [chrisdone/hindent#530]
## Problem
```
cabal install hindent
```

Log message:
```
Configuring hindent-5.2.7...
Building hindent-5.2.7...
Failed to install hindent-5.2.7
Build log ( /home/exa/work/imcurses/.cabal-sandbox/logs/ghc-8.4.3/hindent-5.2.7-GqIdV7TJaGfJi2BnEdtl5Z.log ):
cabal: Entering directory '/tmp/cabal-tmp-27319/hindent-5.2.7'
Configuring hindent-5.2.7...
Preprocessing library for hindent-5.2.7..
Building library for hindent-5.2.7..
[1 of 4] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/CabalFile.o )
[2 of 4] Compiling HIndent.Types    ( src/HIndent/Types.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/Types.o )
[3 of 4] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, dist/dist-sandbox-ad69a7e0/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:453:10: error:
    Duplicate instance declarations:
      instance Pretty Type -- Defined at src/HIndent/Pretty.hs:453:10
      instance Pretty Kind -- Defined at src/HIndent/Pretty.hs:1475:10
    |
453 | instance Pretty Type where
    |          ^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-27319/hindent-5.2.7'
cabal: Error: some packages failed to install:
hindent-5.2.7-GqIdV7TJaGfJi2BnEdtl5Z failed during the building phase. The
exception was:
ExitFailure 1
```

# Cause

This is because haskell-src-exts converted `Kind` from `data Kind l = ...` to `type Kind = Type` in version `1.21`.

# Solution

The obvious immediate workaround is to fix the dependency to explicitly say `<1.21`.

In my very humble opinion, just erasing the `Pretty Kind` instance should work too, but not sure about consequences (the implementations differ, `Kind` has `pretty'`, `Type` has `typ`).

Thanks in advance!

**Comment by jrp2014** [comment]
I can confirm this finding. It's a pain not to be able to do a clean install (with ghc 8.6.3) and use this great utility,

**Comment by kozross** [comment]
I can also confirm it. There are multiple current issues that would be fixed by such an update (not least of all #525 and #523).

**Comment by julian1** [comment]
I have the same error message, with cabal new-install

`
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library

$ cabal new-install hindent
Resolving dependencies...
Build profile: -w ghc-8.0.1 -O1
In order, the following will be built (use -v for more details):
 - hindent-5.3.0 (lib) (requires build)
 - hindent-5.3.0 (exe:hindent) (requires build)

src/HIndent/Pretty.hs:438:10: error:
    Duplicate instance declarations:
      instance Pretty Type -- Defined at src/HIndent/Pretty.hs:438:10
      instance Pretty Kind -- Defined at src/HIndent/Pretty.hs:1445:10
cabal: Failed to build hindent-5.3.0 (which is required by exe:hindent from
hindent-5.3.0). See the build log above for details.
`
If the fix is merged, is there an upstream package caching issue? 

What do I need to do to fix this?

**Comment by tomsmeding** [comment]
@julian1 There has been no package release since the merge, so the waiting is for a new release.

**Comment by tomsmeding** [comment]
It seems I was confused by the ordering of the commits; indeed, there has been no release since the fix for this was merged. In the commit history for the `master` branch, note that the bump to 5.3.0 happened _after_ the merge of felixonmars' pull request.

So, indeed, the waiting is for a new release.

**Comment by julian1** [comment]
@tomsmeding @chrisdone  @exaexa Being unable to build hindent with cabal defaults seems like a show-stopper bug to me. Is a patch release possible - if other code changes are judged to be too risky be included? Are all users relying on compiling locally? I feel like I must be missing something.

**Comment by chrisdone** [comment]
I'll make a new release.

**Comment by chrisdone** [comment]
Uploaded as 5.3.1.

**Comment by julian1** [comment]
A+ works great!.

**Comment by saurabhkukade** [comment]
Still it is breaking for 5.3.1


```
Configuring library for hindent-5.3.1..
Preprocessing library for hindent-5.3.1..
Building library for hindent-5.3.1..
[1 of 5] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, dist/build/HIndent/CabalFile.o )
[2 of 5] Compiling HIndent.CodeBlock ( src/HIndent/CodeBlock.hs, dist/build/HIndent/CodeBlock.o )

src/HIndent/CodeBlock.hs:10:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
10 | import Data.Monoid
   | ^^^^^^^^^^^^^^^^^^
[3 of 5] Compiling HIndent.Types    ( src/HIndent/Types.hs, dist/build/HIndent/Types.o )
[4 of 5] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, dist/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:982:7: error:
    Not in scope: data constructor ‘ClassA’
    |
982 |       ClassA _ name types -> spaced (pretty name : map pretty types)
    |       ^^^^^^

src/HIndent/Pretty.hs:983:9: error:
    Not in scope: data constructor ‘InfixA’
    Perhaps you meant one of these:
      ‘InfixApp’ (imported from Language.Haskell.Exts.Syntax),
      variable ‘P.infix_’ (imported from Language.Haskell.Exts)
    |
983 |       i@InfixA {} -> pretty' i
    |         ^^^^^^

src/HIndent/Pretty.hs:988:7: error:
    Not in scope: data constructor ‘EqualP’
    Perhaps you meant ‘P.Equals’ (imported from Language.Haskell.Exts)
    |
988 |       EqualP _ a b -> do
    |       ^^^^^^

src/HIndent/Pretty.hs:993:7: error:
    Not in scope: data constructor ‘AppA’
    Perhaps you meant ‘App’ (imported from Language.Haskell.Exts.Syntax)
    |
993 |       AppA _ name tys ->
    |       ^^^^

src/HIndent/Pretty.hs:995:7: error:
    Not in scope: data constructor ‘WildCardA’
    Perhaps you meant ‘PWildCard’ (imported from Language.Haskell.Exts.Syntax)
    |
995 |       WildCardA _ name ->
    |       ^^^^^^^^^
cabal: Failed to build hindent-5.3.1 (which is required by exe:hindent from
hindent-5.3.1). See the build log above for details.

```

**Comment by olivier-twist** [comment]
Any update on this ? I also  get the same error with  hindent-5.3.1
1 of 5] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, /Users/i851314/programming/lang/haskell/practical_haskell/hindent-5.3.1/dist-newstyle/build/x86_64-osx/ghc-8.6.5/hindent-5.3.1/build/HIndent/CabalFile.o )
[2 of 5] Compiling HIndent.CodeBlock ( src/HIndent/CodeBlock.hs, /Users/i851314/programming/lang/haskell/practical_haskell/hindent-5.3.1/dist-newstyle/build/x86_64-osx/ghc-8.6.5/hindent-5.3.1/build/HIndent/CodeBlock.o )

src/HIndent/CodeBlock.hs:10:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
10 | import Data.Monoid
   | ^^^^^^^^^^^^^^^^^^
[3 of 5] Compiling HIndent.Types    ( src/HIndent/Types.hs, /Users/i851314/programming/lang/haskell/practical_haskell/hindent-5.3.1/dist-newstyle/build/x86_64-osx/ghc-8.6.5/hindent-5.3.1/build/HIndent/Types.o )
[4 of 5] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, /Users/i851314/programming/lang/haskell/practical_haskell/hindent-5.3.1/dist-newstyle/build/x86_64-osx/ghc-8.6.5/hindent-5.3.1/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:982:7: error:
    Not in scope: data constructor ‘ClassA’
    |
982 |       ClassA _ name types -> spaced (pretty name : map pretty types)
    |       ^^^^^^

**Comment by alexander-potemkin** [comment]
Fails for me as well, MacOS Catalina, ghc 8.8.3:

```
% cabal install hindent                
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - hindent-5.3.1 (lib) (requires build)
 - hindent-5.3.1 (exe:hindent) (requires build)
Starting     hindent-5.3.1 (lib)
Building     hindent-5.3.1 (lib)

Failed to build hindent-5.3.1.
Build log (
/Users/<...>/.cabal/logs/ghc-8.8.3/hndnt-5.3.1-ba650d33.log ):
Configuring library for hindent-5.3.1..
Preprocessing library for hindent-5.3.1..
Building library for hindent-5.3.1..
[1 of 5] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, dist/build/HIndent/CabalFile.o )
[2 of 5] Compiling HIndent.CodeBlock ( src/HIndent/CodeBlock.hs, dist/build/HIndent/CodeBlock.o )

src/HIndent/CodeBlock.hs:10:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
10 | import Data.Monoid
   | ^^^^^^^^^^^^^^^^^^
[3 of 5] Compiling HIndent.Types    ( src/HIndent/Types.hs, dist/build/HIndent/Types.o )

src/HIndent/Types.hs:78:27: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: Monad m
        bound by the type signature for:
                   readExtension :: forall (m :: * -> *).
                                    Monad m =>
                                    String -> m Extension
        at src/HIndent/Types.hs:74:1-49
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            readExtension :: forall (m :: * -> *).
                             Monad m =>
                             String -> m Extension
    • In the expression: fail ("Unknown extension: " ++ x)
      In a case alternative:
          UnknownExtension _ -> fail ("Unknown extension: " ++ x)
      In the expression:
        case classifyExtension x of
          UnknownExtension _ -> fail ("Unknown extension: " ++ x)
          x' -> return x'
   |
78 |     UnknownExtension _ -> fail ("Unknown extension: " ++ x)
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hindent-5.3.1 (which is required by exe:hindent from
hindent-5.3.1). See the build log above for details.
```

**Comment by jgrosso** [comment]
GHC 8.10.1, macOS 10.15.4, can also repro (building hindent-5.3.1).

**Comment by ciehanski** [comment]
GHC 8.8.3, macOS 10.15.4 experiencing same issue as @alexander-potemkin installing hindent 5.3.1

**Comment by thisisnotamerica** [comment]
https://github.com/chrisdone/hindent/issues/563#issuecomment-602073240

**Comment by thisisnotamerica** [comment]
#https://github.com/chrisdone/hindent/issues/563#issuecomment-60207324

**Comment by ZosoDerGoldene** [comment]
GHC 8.8.3, Windows 10, "stack install hident" (hident 5.3.1) seems still broken

**Comment by tomsmeding** [comment]
@ZosoDerGoldene There are forks of this repository that fix compilation; [my fork](https://github.com/tomsmeding/hindent) does just that, while other forks ([example](https://github.com/AshleyYakeley/hindent/tree/Ashley), random pick) actually add more functionality.

**Comment by dhruvio** [comment]
Created a PR, #566, to fix the remaining issues. With these changes, I am able to build `hindent` using GHC 8.10.1.
