### ISSUE TITLE
Doesn't build with latest haskell-src-exts-1.18.0

### ISSUE THREAD

**Issue by felixonmars** [chrisdone/hindent#194]
```
[3 of 9] Compiling HIndent.Pretty   ( src/HIndent/Pretty.hs, dist/build/HIndent/Pretty.o )

src/HIndent/Pretty.hs:81:1: error:
    Failed to load interface for `Language.Haskell.Exts.Annotated'
    Perhaps you meant
      Language.Haskell.Exts.Syntax (from haskell-src-exts-1.18.0)
      Language.Haskell.Exts.Pretty (from haskell-src-exts-1.18.0)
      Language.Haskell.Exts.Build (from haskell-src-exts-1.18.0)
    Use -v to see a list of the files searched for.

src/HIndent/Pretty.hs:82:1: error:
    Failed to load interface for `Language.Haskell.Exts.Annotated.Syntax'
    Perhaps you meant
      Language.Haskell.Exts.ParseSyntax
      Language.Haskell.Exts.Syntax (from haskell-src-exts-1.18.0)
    Use -v to see a list of the files searched for.
```

**Comment by joe9** [comment]
Same error as above:
`
cabal install
Resolving dependencies...
Configuring hindent-4.6.4...
Building hindent-4.6.4...
Failed to install hindent-4.6.4
Build log ( /tmp/cabal-logs/hindent-4.6.4.log ):
cabal: Entering directory '.'
Configuring hindent-4.6.4...
Building hindent-4.6.4...
Preprocessing library hindent-4.6.4...

src/HIndent.hs:52:18:
    Could not find module ‘Language.Haskell.Exts.Annotated’
    Perhaps you meant
      Language.Haskell.Exts.Syntax (from haskell-src-exts-1.18.0@AA6E6aflSGAK6uT1m8Pqw7)
      Language.Haskell.Exts.Pretty (from haskell-src-exts-1.18.0@AA6E6aflSGAK6uT1m8Pqw7)
      Language.Haskell.Exts.Build (from haskell-src-exts-1.18.0@AA6E6aflSGAK6uT1m8Pqw7)
    Use -v to see a list of the files searched for.

src/HIndent/Pretty.hs:82:18:
    Could not find module ‘Language.Haskell.Exts.Annotated.Syntax’
    Perhaps you meant
      Language.Haskell.Exts.ParseSyntax
      Language.Haskell.Exts.Syntax (from haskell-src-exts-1.18.0@AA6E6aflSGAK6uT1m8Pqw7)
    Use -v to see a list of the files searched for.

src/HIndent/Styles/ChrisDone.hs:20:8:
    Could not find module ‘Language.Haskell.Exts.Annotated.Fixity’
    Perhaps you meant
      Language.Haskell.Exts.Fixity (from haskell-src-exts-1.18.0@AA6E6aflSGAK6uT1m8Pqw7)
    Use -v to see a list of the files searched for.
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
hindent-4.6.4 failed during the building phase. The exception was:
ExitFailure 1
`

**Comment by cocreature** [comment]
#195 should fix this

**Comment by joe9** [comment]
@cocreature @felixonmars @chrisdone the pull request fixed the issue.

Thanks @cocreature

**Comment by chrisdone** [comment]
Merged, I'll make a new release today after doing some other hindent work.
